project:
  type: website
  output-dir: docs

website:
  title: "IA 480: Applied Network Analysis: Systems, Connections, and Influence"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Materials
        menu:
          - href: IA480-NA/Week2Lecture/index.qmd
            text: Week 2 Course Materials
          - href: IA480-NA/Week3Lecture/index.qmd
            text: Week 3 Course Materials
          - href: IA480-NA/Week4Lecture/index.qmd
            text: Week 4 Course Materials
          - href: IA480-NA/Week5Lecture/index.qmd
            text: Week 5 Course Materials
          - href: IA480-NA/Week6Lecture/index.qmd
            text: Week 6 Course Materials
          - href: IA480-NA/Week7Lecture/index.qmd
            text: Week 7 Course Materials
          - href: IA480-NA/Week8Lecture/index.qmd
            text: Week 8 Course Materials
          - href: IA480-NA/Week9Lecture/index.qmd
            text: Week 9 Course Materials
          - href: IA480-NA/Week10Lecture/index.qmd
            text: Week 10 Course Materials
          - href: IA480-NA/Week11Lecture/index.qmd
            text: Week 11 Course Materials
          - href: IA480-NA/Week12Lecture/index.qmd

format:
  html:
    theme: jmu-lecture.css
    toc: true